import SettingsGame from './SettingsGame';
import {
  SettingGameOptions,
  StylBtnOpenSetting,
  StylWrapperSettings,
} from './GameOptions/';
import {
  StylWrapperVip,
  StylVipText,
  StylBtnVip,
  SettingsGameVipStatus,
} from './VipStatusSettings/';
import SettingsGameFooter from './SettingsGameFooter';
import ModalSettings from '../ModalWindow/ModalSettings';
import {
  StylBoxFeaturesGame,
  StylBtnStartGame,
  StylBoxSettingsGame,
  BtnMoreSettings,
  StylWrapperAllSettings,
  StylBtnFooterSettings,
  StylBoxFooterSettings,
  StylSectionDiscount,
  StylCardSettingsTitle,
  StylWrapperCard,
  StylCardSettingsText,
  StylBtnCardSettings,
  StylBoxWrapperCards,
  StylBoxCenterCard,
  StylImgCardSettings,
  StylTitleUserSettings,
  StylInputUserSettings,
  StylWrapperInput,
  StylVipStatusModal,
  StylOptionsAddedWrapper,
  StylBtnStartGameFooter,
  StylBtnFooterSettingsComplexity,
  StylBoxFlexStartColumn,
  StylWrapperCenterContent,
} from './SettingsGame.styled';

export {
  StylOptionsAddedWrapper,
  StylVipStatusModal,
  StylWrapperInput,
  StylInputUserSettings,
  StylTitleUserSettings,
  StylImgCardSettings,
  StylBoxCenterCard,
  StylBoxFooterSettings,
  SettingsGame,
  StylBoxFeaturesGame,
  StylBtnStartGame,
  StylBoxSettingsGame,
  StylBtnOpenSetting,
  BtnMoreSettings,
  StylWrapperSettings,
  SettingGameOptions,
  StylWrapperAllSettings,
  SettingsGameVipStatus,
  StylWrapperVip,
  StylVipText,
  StylBtnVip,
  StylBtnFooterSettings,
  SettingsGameFooter,
  StylSectionDiscount,
  StylCardSettingsTitle,
  StylWrapperCard,
  StylCardSettingsText,
  StylBtnCardSettings,
  StylBoxWrapperCards,
  ModalSettings,
  StylBtnStartGameFooter,
  StylBtnFooterSettingsComplexity,
  StylBoxFlexStartColumn,
  StylWrapperCenterContent,
};
